version: '3.8'

services:
  frontend:
    build:
      context: ./FrontEndTest
      args:
        - ENVIRONMENT=production
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./BackEndTest
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
